# Generated by Django 2.0.5 on 2018-05-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_auto_20180511_0346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TweetsTabl',
            new_name='TweetsTable',
        ),
    ]
