# Generated by Django 2.0.5 on 2018-05-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0003_auto_20180511_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetSearchTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ttext', models.TextField()),
                ('tid', models.TextField()),
                ('retweet', models.TextField()),
                ('favorite_count', models.TextField()),
                ('uname', models.TextField()),
                ('profimg', models.TextField()),
                ('query', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'tweetsearch_table',
            },
        ),
    ]
