# Generated by Django 2.0.5 on 2018-05-17 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_tweetsearchtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetSearchTable',
        ),
    ]
