# Generated by Django 2.0.5 on 2018-05-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_delete_tweetsearchtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetSearchTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ttext', models.TextField()),
                ('tid', models.TextField()),
                ('retweet', models.TextField()),
                ('favorite_count', models.TextField()),
            ],
            options={
                'db_table': 'tweetsearch_table',
                'managed': True,
            },
        ),
    ]
