# Generated by Django 2.0.5 on 2018-05-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0006_tweetsearchtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetsearchtable',
            name='favorite_count',
        ),
    ]
