# Generated by Django 2.0.5 on 2018-05-17 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0007_remove_tweetsearchtable_favorite_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetSearchTable',
        ),
    ]
