# Generated by Django 2.0.5 on 2018-05-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0023_tweetstable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetsTable',
        ),
    ]
